name: local_notification
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  flutter_bloc: ^8.1.3
  http: ^1.1.0
  flutter_local_notifications: ^15.1.0+1
  firebase_messaging: ^14.6.5
  firebase_core: ^2.15.0
  awesome_notifications: ^0.7.4+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.2


flutter:

  uses-material-design: true

  assets:
    - assets/images/

