// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABu959bNCMjY8nPnlD40iK-rL20j2a0ss',
    appId: '1:394927006352:web:81bf893aafaa6a85402e15',
    messagingSenderId: '394927006352',
    projectId: 'local-notification-4e1d9',
    authDomain: 'local-notification-4e1d9.firebaseapp.com',
    storageBucket: 'local-notification-4e1d9.appspot.com',
    measurementId: 'G-B8RPM5F8VQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2U_Q7iFJSk06TMez3rVjQF-zl-RIw0IE',
    appId: '1:394927006352:android:5e4bf857e753ca6b402e15',
    messagingSenderId: '394927006352',
    projectId: 'local-notification-4e1d9',
    storageBucket: 'local-notification-4e1d9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDabAhcDTqLhzvHmhzN_3vLNRftM2LvuuM',
    appId: '1:394927006352:ios:2a7802189f43675e402e15',
    messagingSenderId: '394927006352',
    projectId: 'local-notification-4e1d9',
    storageBucket: 'local-notification-4e1d9.appspot.com',
    iosClientId: '394927006352-3fkh7uv78ismcghurd4l09hlcrchs37s.apps.googleusercontent.com',
    iosBundleId: 'com.example.localNotification',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDabAhcDTqLhzvHmhzN_3vLNRftM2LvuuM',
    appId: '1:394927006352:ios:f1e834f8dfe2738b402e15',
    messagingSenderId: '394927006352',
    projectId: 'local-notification-4e1d9',
    storageBucket: 'local-notification-4e1d9.appspot.com',
    iosClientId: '394927006352-q7isv1mpdvo8snmuaecrvontqjanvhpv.apps.googleusercontent.com',
    iosBundleId: 'com.example.localNotification.RunnerTests',
  );
}
